CREATE TABLE [dbo].[INSCRITO]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Id_Al] INT NOT NULL, 
    [Cod_Curso] INT NOT NULL, 
    CONSTRAINT [FK_INSCRITO_CURSO] FOREIGN KEY ([Cod_Curso]) REFERENCES [CURSO]([Cod]), 
    CONSTRAINT [FK_INSCRITO_ALUMNO] FOREIGN KEY ([Id_Al]) REFERENCES [ALUMNO]([Id]) 
)
